### ISSUE TITLE
表示名

### ISSUE THREAD

**Issue by 9kmpwp** [ItsukiKigoshi/icu-catalogue#83]
「キリスト教史Ⅱ」など最後にローマ数字が付くものをペーストした時、「Ⅱ」のみが表示される。

**Comment by ItsukiKigoshi** [comment]
Issueありがとうございます！
## コード内該当箇所
https://github.com/ItsukiKigoshi/icu-catalogue/blob/4f97477378ae01258cf743e76fe0a21475b46e78/src/components/AddCourse/index.tsx#L38-L107

## バグの原因
- ペーストされたコース情報内のスペース（空白）の使い方が上手く条件分岐されていない
- ChromeとSafariでコピー時のスペースの付き方に差があるのも課題
- ちなみに，数学の科目をChromeで追加しようとしても同様のバグが起きます．

## 解決方法
- 短期的に: parseCourseInfoを改修
- 長期的に: コースの追加をICU Catalogue アプリ内で完結（コースの情報を本アプリに持たせる）

## 背景
- ペーストされたコース情報の変換は，上記parseCourseInfoという関数が担っている（引数:ペーストされたコース情報，出力:コースの情報が格納されたarray）
- 言語はTypeScript（JavaScriptと言う言語が拡張されたもの）

もしTypeScriptを触ったことがおありでしたら，ぜひfork（自分のGitHubアカウント上にICU Catalogueのコードをコピーする）した上で該当部分を改修し，Pull Request（GitHub内でコード製作者に対して行われる第三者からの変更願い）を私に対して行ってみてください！

**Comment by 9kmpwp** [comment]
修正ありがとうございます〜！
了解しました！

三浦英奈 Ena Miura
***@***.***


2024年3月13日(水) 6:56 Itsuki Kigoshi ***@***.***>:

**Comment by ItsukiKigoshi** [comment]
私はまだ修正を行なっていないです…

**Comment by 9kmpwp** [comment]
疲れてて脳死で返信していました…
失礼しました…

三浦英奈 Ena Miura
***@***.***


2024年3月13日(水) 19:13 Itsuki Kigoshi ***@***.***>:
